name: weather_app
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  intl: 0.16.1
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.0

  bloc: 6.0.0
  flutter_bloc: 6.0.0
  get_it: 5.0.1
  auto_route: 0.6.9
  easy_localization: 2.3.3
  provider: 4.3.2+2
  websafe_svg: 1.1.4
  retrofit: 1.3.4+1
  dio: 3.0.10
  json_annotation: 3.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  retrofit_generator: 1.4.0
  auto_route_generator: 0.6.10
  build_runner: 1.10.3
  json_serializable: 3.5.0

flutter:

  uses-material-design: true
  assets:
    - assets/translations/
